### ISSUE TITLE
build err  cannot find function `get_verifying_key_data` in module `filecoin_proofs_v1::constants`

### ISSUE THREAD

**Issue by viking2015** [filecoin-project/rust-filecoin-proofs-api#42]
rust-filecoin-proofs-api: v5.1.1
commit: 2095cc1eda8bdc18a12067d2ec6bab747815691d
rust-file-proofs: v5.1.14
commit:  9117ed68fbf73cc32f34c1440120393cbab639f1

cargo build occur err :
`  Compiling filecoin-proofs-api v5.1.1 (/mnt/e/Workspace/RustProject/rust-filecoin-proofs-api)
error[E0425]: cannot find function `get_verifying_key_data` in module `filecoin_proofs_v1::constants`
   --> /mnt/e/Workspace/RustProject/rust-filecoin-proofs-api/src/registry.rs:163:61
    |
163 |                 let params = filecoin_proofs_v1::constants::get_verifying_key_data(&id);
    |                                                             ^^^^^^^^^^^^^^^^^^^^^^ not found in `filecoin_proofs_v1::constants`

error[E0425]: cannot find function `get_parameter_data` in module `filecoin_proofs_v1::constants`
   --> /mnt/e/Workspace/RustProject/rust-filecoin-proofs-api/src/registry.rs:178:61
    |
178 |                 let params = filecoin_proofs_v1::constants::get_parameter_data(&id);
    |                                                             ^^^^^^^^^^^^^^^^^^ not found in `filecoin_proofs_v1::constants`

error[E0425]: cannot find function `get_verifying_key_data` in module `filecoin_proofs_v1::constants`
   --> /mnt/e/Workspace/RustProject/rust-filecoin-proofs-api/src/registry.rs:364:61
    |
364 |                 let params = filecoin_proofs_v1::constants::get_verifying_key_data(&id);
    |                                                             ^^^^^^^^^^^^^^^^^^^^^^ not found in `filecoin_proofs_v1::constants`

error[E0425]: cannot find function `get_parameter_data` in module `filecoin_proofs_v1::constants`
   --> /mnt/e/Workspace/RustProject/rust-filecoin-proofs-api/src/registry.rs:379:61
    |
379 |                 let params = filecoin_proofs_v1::constants::get_parameter_data(&id);
    |                                                             ^^^^^^^^^^^^^^^^^^ not found in `filecoin_proofs_v1::constants`

error: aborting due to 4 previous errors`

**Comment by vmx** [comment]
It looks like you were trying something patching `filecoin-proofs` to the most recent commit. For example via editing your `Cargo.toml` like that, where you've checked out the most recent `filecoin-proofs`.

```toml
[patch.crates-io]
filecoin-proofs-v1 = { package = "filecoin-proofs", path = "../rust-fil-proofs/filecoin-proofs" }
```

That use case is not supported. You either need to patch `filecoin-proofs` yourself, or need to wait for a release of `fileloin-proofs-api` which contains these changes.
