### ISSUE TITLE
cargo update not work, cause by: [patch.crates-io] not work

### ISSUE THREAD

**Issue by liusen-adalab** [filecoin-project/rust-filecoin-proofs-api#67]
Hello,  I got this waring when I checkout to the tag [ v9.0.0-revert-deps-hotfix](https://github.com/filecoin-project/rust-filecoin-proofs-api/tree/v9.0.0-revert-deps-hotfix) and run **cargo update** . And the lotus will compile the rust-fil-proofs **v9.0.2** from crates.io  instead of the **filecoin-proofs-v9.0.1-revert-deps-hotfix** from [git repo](https://github.com/LiuSen-Adalab/rust-fil-proofs/tree/filecoin-proofs-v9.0.1-revert-deps-hotfix). How can I fix it? Thanks.

`    Updating git repository `https://github.com/filecoin-project/rust-fil-proofs`
    Updating git repository `https://github.com/filecoin-project/neptune`
    Updating crates.io index
warning: Patch `filecoin-hashers v4.0.1 (https://github.com/filecoin-project/rust-fil-proofs?rev=filecoin-proofs-v9.0.1-revert-deps-hotfix#38484e69)` was not used in the crate graph.
Patch `filecoin-proofs v9.0.1 (https://github.com/filecoin-project/rust-fil-proofs?rev=filecoin-proofs-v9.0.1-revert-deps-hotfix#38484e69)` was not used in the crate graph.
Patch `fr32 v2.0.1 (https://github.com/filecoin-project/rust-fil-proofs?rev=filecoin-proofs-v9.0.1-revert-deps-hotfix#38484e69)` was not used in the crate graph.
Patch `storage-proofs-core v9.0.1 (https://github.com/filecoin-project/rust-fil-proofs?rev=filecoin-proofs-v9.0.1-revert-deps-hotfix#38484e69)` was not used in the crate graph.
Patch `storage-proofs-porep v9.0.1 (https://github.com/filecoin-project/rust-fil-proofs?rev=filecoin-proofs-v9.0.1-revert-deps-hotfix#38484e69)` was not used in the crate graph.
Patch `storage-proofs-post v9.0.1 (https://github.com/filecoin-project/rust-fil-proofs?rev=filecoin-proofs-v9.0.1-revert-deps-hotfix#38484e69)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.`

**Comment by vmx** [comment]
It's been a long time since then. The current version should build fine. Hence I'm closing this issue.
