### ISSUE TITLE
loading sector info too slow when greater than ten thousands of sectors in one deadlines 

### ISSUE THREAD

**Issue by mslovy** [filecoin-project/rust-filecoin-proofs-api#69]
we find that when too many sectors in a window post deadline,  because of  loading PrivateReplicaInfo need to read p_aux on disk one by one:
https://github.com/filecoin-project/rust-filecoin-proofs-api/blob/250963c69f13bef8ab91f709e9e33c9e1d760fbd/src/post.rs#L407

so is that possible to load replicainfo in parallel?

**Comment by vmx** [comment]
It looks like this issue has been fixed on the lotus side by https://github.com/filecoin-project/lotus/pull/8391 as the comment at https://github.com/filecoin-project/lotus/issues/8592#issuecomment-1118978578 suggests. If it's still a problem, feel free to re-open this issue.
